### ISSUE TITLE
Bug report: the rest-sidebar can not be edited by multiple lines

### ISSUE THREAD

**Issue by mzwlevi** [vipzhicheng/logseq-plugin-sidebar-preset#2]
![Screen Shot 2022-09-23 at 12 15 08](https://user-images.githubusercontent.com/78029539/191891108-1279c9f9-0846-4c4f-84e6-98a29fb425bf.png)
When I use cmd+enter, can not jump to a new line
0.8.7

**Comment by vipzhicheng** [comment]
Confirm, but it needs Logseq team to fix it. I already let them know.

**Comment by vipzhicheng** [comment]
It was fixed by Logseq Team in Logseq v0.8.9.
