### ISSUE TITLE
Feature request: Add customized keybindings to reset-sidebar

### ISSUE THREAD

**Issue by mzwlevi** [vipzhicheng/logseq-plugin-sidebar-preset#3]

**Comment by vipzhicheng** [comment]
It depends on a non-existed Logseq API. Will add the keybinding later.

**Comment by vipzhicheng** [comment]
Now you can add keybindings in plugin settings json file. 

e.g. If you want to set the key `command+shift+s`, you need to use

```json
"keyBindings": {
  "resetSidebar": "shift+mod+s"
},
```
