### ISSUE TITLE
pages don't stay on top of the sidebar

### ISSUE THREAD

**Issue by csarmendariz** [vipzhicheng/logseq-plugin-sidebar-preset#4]
Hi,

Thanks a lot for making this plugin, it's almost what I was looking for (a substitute for pinning pages in roam).
However the pages don't stay on top like the pinned pages in roam do, instead if you open new pages in the sidebar they open on top of them.

Is there a way to keep the pages you configured on top of the sidebar?

Thanks!

**Comment by vipzhicheng** [comment]
It is controlled by Logseq core. So I can not pin my settings on top.
